In [20]:
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

dataset = pd.read_csv('Training_Scores.csv')

In [21]:
x = dataset.drop(columns=(["Total sentences", "Total words", "Total words", "Total Syllable"]))

In [22]:
y = dataset["classification"]

In [23]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [24]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9047619047619048

In [25]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.6666666666666666

In [26]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

1.0

In [28]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [29]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [37]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [56]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []
scores_gnb = []

for train_index, test_index in folds.split(x,y):
    x_train, x_test, y_train, y_test = x.iloc[train_index], x.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x_train, x_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [57]:
scores_gnb

[1.0, 1.0, 1.0]

In [43]:
scores_logistic

[1.0, 1.0, 1.0]

In [44]:
scores_svm

[0.782608695652174, 0.8181818181818182, 0.8181818181818182]

In [45]:
scores_rf

[1.0, 1.0, 1.0]

In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x, y,cv=3)


array([1., 1., 1.])

In [48]:
cross_val_score(SVC(gamma='auto'), x, y,cv=3)

array([0.7826087 , 0.81818182, 0.81818182])

In [49]:
cross_val_score(RandomForestClassifier(n_estimators=40),x,y,cv=3)

array([1., 1., 1.])

In [50]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),x, y, cv=10)
np.average(scores1)

0.9857142857142858

In [51]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),x, y, cv=10)
np.average(scores2)

1.0

In [52]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),x, y, cv=10)
np.average(scores3)

1.0

In [53]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),x, y, cv=10)
np.average(scores4)

1.0